### ISSUE TITLE
Doesn´t work on macos15.3.1?!?

### ISSUE THREAD

**Issue by warmup72** [colomolo/alfred-bookmarks#13]
Hi,

I only get errors using Bookvault :-(

With bktab (and Safari)
```
[08:23:37.417] ERROR: Bookmark Vault[Automation Task] Task Error (1): arm/get-frontmost-browser.swift:32: Fatal error: Did not find a supported web browser
../../../../com.alfredapp.automation.core/safari/.common/tabs-current: execution error: Error: Did not find a supported web browser (-2700)
```

With BKadd
`08:21:37.766] ERROR: Bookmark Vault[Script Filter] Code 1: /Users/simon/Library/Caches/com.runningwithcrayons.Alfred/Workflow Scripts/6CBC75EF-BD6C-43D6-AAE7-592528942E5B: execution error: Error: TypeError: null is not an object (evaluating `

**Comment by warmup72** [comment]
Okay - it was my fault- if there is no list this error comes up.
Maybe it is a good idea to add this in die Installation-description or ask for a new List after the first add of an Bookmark?

**Comment by colomolo** [comment]
Yes, good point. Thanks for reporting, I will check this.

**Comment by maindoor** [comment]
Any updates ? Doesn't work on 15.4.1 either.

**Comment by colomolo** [comment]
Hi @maindoor @warmup72 sorry for delay, was busy lately. Will look into this soon.
